### ISSUE TITLE
데이터 크롤링 코드 테스트 까지 완료

### ISSUE THREAD

**Issue by Worldofgentleken** [AICC-PFLOW/database#2]
봉준, 상현: 원티드 타겟으로 크롤링 테스트 코드 완성

**Comment by pythonize** [comment]
8/27 Wanted Crawling Code work in progress
-> 스텔스 기능(브라우저 가장) 적용
-> 이미지 로딩 비활성화 적용
-> User-Agent 변경(page 불필요 요소 로드 X) 적용 
-> headless 기능 적용(브라우저 미실행 크롤링 진행)
-> 80초당 20페이지 크롤링 가능

**Comment by Worldofgentleken** [comment]
크롤링 현재 어떻게 진행 되고 있나요?

**Comment by pythonize** [comment]
테스트코드 작성 완료하였으나, 위치 코드에 변동이 있어 수정작업중입니다.
해당부분 수정후 직무별 크롤링 진행 예정입니다

**Comment by pythonize** [comment]
8/30 개발 관련 직무 3,560개의 데이터 크롤링 완료 하였고, csv파일로 변환시켜 저장하는 테스트 코드 작업도 완료하였습니다.

**Comment by Bong-jun-jang** [comment]
원티드 사이트 채용공고 크롤링 모든 직군 모아서 csv파일로 저장하기까지 작업 완료하였습니다.
직군은 20개, 데이터는 약 9700개 정도 입니다.
