### ISSUE TITLE
DB 설계 _ 커뮤니티 게시판

### ISSUE THREAD

**Issue by pythonize** [AICC-PFLOW/database#4]
8/28 커뮤니티 게시판 DB 설계 작업 진행중

**Comment by witchking20** [comment]
post_id => board_id로 수정 부탁드립니다

**Comment by pythonize** [comment]
해당 부분 수정후 테이블 설계 재조정 중입니다

**Comment by Bong-jun-jang** [comment]
9/4 DB 커뮤니티 테이블 설계 완료

https://www.erdcloud.com/u/jbj0536
